import Head from 'next/head';
import Link from 'next/link';
import { HomeStyle, HomeDiv, HomeMenu } from '../styles/home.style';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Relair.</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <HomeDiv>
          <HomeStyle>
            <Image
              src='https://res.cloudinary.com/dkpeivu7g/image/upload/v1665133644/pexels-yuting-gao-1557547_uae9g0.jpg'
              alt=''
              layout='fill'
            />
            <HomeMenu>
              <div>
                <Link href={'/products/jeans'}>Jeans</Link>
                <Link href={'/'}>Classic</Link>
                <Link href={'/products/shoes'}>Boots</Link>
                <Link href={'/products/coats'}>Coats</Link>
              </div>
            </HomeMenu>
          </HomeStyle>
        </HomeDiv>
      </main>
    </div>
  );
}
